-- Step 0: Raw and Staging table setup

CREATE TABLE RAW_CDR (
    CALL_ID              NUMBER,
    CUSTOMER_ID          VARCHAR2(50),
    TOWER_ID             VARCHAR2(50),
    CALL_TYPE_CODE       VARCHAR2(30),
    CALL_START_TS        VARCHAR2(40),
    DURATION_SECONDS_RAW VARCHAR2(40),
    REVENUE_RAW          VARCHAR2(40),
    COUNTRY_CODE         VARCHAR2(10)
);

CREATE TABLE STG_CDR_CLEAN (
    CALL_ID              NUMBER PRIMARY KEY,
    CUSTOMER_ID          VARCHAR2(50) NOT NULL,
    TOWER_ID             VARCHAR2(50) NOT NULL,
    CALL_TYPE_CODE       VARCHAR2(30) NOT NULL,
    CALL_START_TS        DATE NOT NULL,
    DURATION_SECONDS     NUMBER(10,2) NOT NULL,
    REVENUE_AMOUNT       NUMBER(12,2) NOT NULL,
    IS_INTERNATIONAL     CHAR(1) CHECK (IS_INTERNATIONAL IN ('Y','N'))
);
