-- Step 1: Cleansing raw telecom data into staging

INSERT INTO STG_CDR_CLEAN (
    CALL_ID,
    CUSTOMER_ID,
    TOWER_ID,
    CALL_TYPE_CODE,
    CALL_START_TS,
    DURATION_SECONDS,
    REVENUE_AMOUNT,
    IS_INTERNATIONAL
)
SELECT
    TO_NUMBER(TRIM(CALL_ID)),
    TRIM(CUSTOMER_ID),
    TRIM(TOWER_ID),
    UPPER(TRIM(CALL_TYPE_CODE)),
    TO_DATE(TRIM(CALL_START_TS), 'YYYY-MM-DD HH24:MI:SS'),
    TO_NUMBER(NVL(NULLIF(TRIM(DURATION_SECONDS_RAW), ''), '0')),
    TO_NUMBER(NVL(NULLIF(TRIM(REVENUE_RAW), ''), '0')),
    CASE WHEN UPPER(TRIM(COUNTRY_CODE)) <> 'IN' THEN 'Y' ELSE 'N' END
FROM RAW_CDR
WHERE CALL_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND TOWER_ID IS NOT NULL
  AND CALL_TYPE_CODE IS NOT NULL;
