-- Step 3: Fact table creation for call analytics

CREATE TABLE FACT_CALL (
    CALL_ID             NUMBER PRIMARY KEY,
    CUSTOMER_KEY        NUMBER NOT NULL,
    TOWER_KEY           NUMBER NOT NULL,
    TIME_KEY            NUMBER NOT NULL,
    CALLTYPE_KEY        NUMBER NOT NULL,
    DURATION_SECONDS    NUMBER(10,2) DEFAULT 0,
    REVENUE_AMOUNT      NUMBER(12,2) DEFAULT 0,
    IS_INTERNATIONAL    CHAR(1) DEFAULT 'N' CHECK (IS_INTERNATIONAL IN ('Y', 'N')),
    CALL_COUNT          NUMBER DEFAULT 1,
    CONSTRAINT FK_FACT_CUSTOMER FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
    CONSTRAINT FK_FACT_TOWER FOREIGN KEY (TOWER_KEY) REFERENCES DIM_TOWER(TOWER_KEY),
    CONSTRAINT FK_FACT_TIME FOREIGN KEY (TIME_KEY) REFERENCES DIM_TIME(TIME_KEY),
    CONSTRAINT FK_FACT_CALLTYPE FOREIGN KEY (CALLTYPE_KEY) REFERENCES DIM_CALL_TYPE(CALLTYPE_KEY)
);
