-- Step 4: KPI queries used in telecom reporting

-- KPI 1: Daily Call Volume
SELECT
    T.FULL_DATE,
    SUM(F.CALL_COUNT) AS TOTAL_CALLS,
    ROUND(SUM(F.DURATION_SECONDS) / 60, 2) AS TOTAL_DURATION_MINUTES
FROM FACT_CALL F
JOIN DIM_TIME T ON T.TIME_KEY = F.TIME_KEY
GROUP BY T.FULL_DATE
ORDER BY T.FULL_DATE;

-- KPI 2: Call Type Performance
SELECT
    C.CALL_TYPE_NAME,
    SUM(F.CALL_COUNT) AS TOTAL_CALLS,
    ROUND(SUM(F.REVENUE_AMOUNT), 2) AS TOTAL_REVENUE
FROM FACT_CALL F
JOIN DIM_CALL_TYPE C ON C.CALLTYPE_KEY = F.CALLTYPE_KEY
GROUP BY C.CALL_TYPE_NAME
ORDER BY TOTAL_REVENUE DESC;

-- KPI 3: International Call Monitoring
SELECT
    T.FULL_DATE,
    SUM(F.CALL_COUNT) AS INTERNATIONAL_CALLS,
    ROUND(SUM(F.REVENUE_AMOUNT), 2) AS INTERNATIONAL_REVENUE
FROM FACT_CALL F
JOIN DIM_TIME T ON T.TIME_KEY = F.TIME_KEY
WHERE F.IS_INTERNATIONAL = 'Y'
GROUP BY T.FULL_DATE
ORDER BY T.FULL_DATE;

-- KPI 4: Revenue Data
SELECT
    D.CUSTOMER_ID,
    D.CUSTOMER_NAME,
    ROUND(SUM(F.REVENUE_AMOUNT), 2) AS CUSTOMER_REVENUE
FROM FACT_CALL F
JOIN DIM_CUSTOMER D ON D.CUSTOMER_KEY = F.CUSTOMER_KEY
GROUP BY D.CUSTOMER_ID, D.CUSTOMER_NAME
ORDER BY CUSTOMER_REVENUE DESC;
